apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cert-manager/cloudflare-api-token.sealedsecret.yaml
  - cert-manager/cluster-issuer.yaml
  - argocd/ingress.yaml
  - monitoring/grafana-admin.sealedsecret.yaml
  - databases/postgresql-auth.sealedsecret.yaml
  - databases/redis-auth.sealedsecret.yaml
  - databases/redis-commander.yaml
  - messaging/rabbitmq-auth.sealedsecret.yaml
  - messaging/rabbitmq-erlang-cookie.sealedsecret.yaml
