---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-auth
  namespace: messaging
spec:
  encryptedData:
    rabbitmq-password: AgCvi/wFJHXVM8TBvhx37Q86G6BaOhrgbZaMVm2jnIpV7qHDnKEQ7uvZIvRRwHqAU9zuLbmRsOFfRvpQ6UPIgjz8MtjnT6Z0dTFGHJKUPP2xgYQaQLt94iTwt3tHcwuxbrxpqCeeEcGJfdKSBnZ7kkapCnxiSZ9Vkdr2gLbXecNklwHp2N9hXQQbzsGk8ZzvcTF89XPIOxprsa4yPxCnOzqXBrh9Y4a0fMxM3rFweYMeKsqZgykmTz4cFotLHKoWH3ut2a+/c/6yDSDeNZVFYCvHwPFnKe4ZAvlA8/bDn7BG224JxLufzUOu8L8sgLYD5y5zGnrmOP8GXLb2FGzMjDoBG8h5gqCRMJ5vSwTeniMz5gISerNEs10MaY1JFqZj/2wox59P3FQCqtfFw92DhjkyS+D5uWikyWELXrYhQlBBrNnG00UzMXGcPkwodl2NYVb+/Q16ziwL9C5AJ5MzKKoYTNhEua8a60WXk8vIlCkoouM1uCI95Tj/BacA5JG8fTUYOg9YZVtVlwdaMDHcw8mjUxrbJFgPZpTFqUxfHpL1dLkzpbpPdv5w/YJHZks3+PI726S2rdgp7VztpqhRkhBYM1qZcKduFj4uIvLgaCbXhldvjhPxfPMPvlztY5X6EyV2Ulwmd7573lPuES3zjkXB+iLTgXO83N1U16fswG/Su3J0gn/pwJyTOHiYOBiI/clsI+0RNxJnpMWgmA4hOBuU+yTxNghiFkSYwecbbrjfbJu3t53TlFIyRMlwfTBVhf4=
  template:
    metadata:
      name: rabbitmq-auth
      namespace: messaging
