---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-erlang-cookie
  namespace: messaging
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgCJozcsXll4Y0q7JiHLXcXg+ZNUrHiKHEtKogv75rZPJIoxxcfy5S4ZNozsMZE6fjQDKzqaIF2y6zc89qc6kWkgHRvMR+HFSdi73gEFEi1s9tbMSg1Mg9TnbXZ16JhmJkWC9UgBBS0C+BFHIziE4FkVsXxB9HlIPmevgH50Cb9Zkfthu4EG3Re3G0oswazntCYG55bKwNf6acPDhn3Uv/5FYzMjpD0JtfbrqSjA7MXrMtwNpfoW8YFFcFkobNWDMqaiAlALf/aJvWo1NZZmxMU++UlYfpOz7VIWl72gZEL70MKSnyS7/1Hduifk+BAbJHsj7rRQWoeSwSBwarenZMmvj6ilAymo7hBkzdAFKtu+/p2ZpA7C/7D27oum/ww8hnlvTZuuVlnq3Z9eqZdMOXEoNGQqgujweGbYCpTTKa/3o/lvRBHyRnudxI9cEdsg2ZDHDE5q3HLJuU8XRa4Khc5Gii7H8XKNQtEvAUbyebXCAjTvet96Ci3g1Irl/7JVjbG16ldFMGaoE6YyC87E/65RAwAKxY7WijgkW4graXH4EzoqXnyTThWOvfIgBbF4OwTQcTW1O+8rrW+EjkEnKxf64eGbCwZ0e4UjIbqDUMQmqPiB0LzgROQpZmWOys+EnSJyETY/4nQ5kIt24Lf/B+PeBsxB0033Or16Cj8y67IaYSYHLfaenrRXP2dWCCALLM3bVXqUKdd1/UU5E1hcTxzVrCDX/iuPY6uiBlzL2QBCSV3yQo/eOCgZm3dDljxbts+jEUPv6PPQCa8P5kcbLRvH
  template:
    metadata:
      name: rabbitmq-erlang-cookie
      namespace: messaging
