---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCJQjud9gwFkvZEH083PlxTpJSZ4WOeoFPR/M3eg9a+aH6VknzAVxQlL7YvFj6Q22C5baEkPaTaLqD4zU/JYA+68e5TYbFy1QLupU9CBVCPeACbNQHtBnrbib62kAk5oF5gnHBQ5NrchIN4GQ2F0owZXQPdjyPbduWWo+Sos+d3fDUO84B7FDMatfk7wyUjcM/7HxY8pa+eTktHmzsJ/bWs/ARaYTHr2GT6xcCDYSN5wJYDdJnmxYZmTlik5wX2apGXqubRyqqzjo3jCpCY2dOzCidJoxPhWEupUkKBKdPswClWh5tysODTR2H3xdp3MEZdjsLjkwbiQFSr7OasSKspY23RtGbDBndu6ql0mQj2tjz0OMLaUqjdYAXybPYlupjxs1pQRdw0EyM3kCkWw6YqlDB91EGy54VMXAPTQShtgvEYZFc/WZQML131TLS5oHqAJe5w4SNM/3coMboJJutY6msQq07TwMyqJGxzp1xHnLVj3sAQfv/tUOc11rpu5vDQbXPKXqjnq75r/laS2rqHjhoIFb4DJ18UBASoRkIR+CWozCLCRdStZ+0n7pPKV0mX66eDhGv3vwfqbNhTOFykYd957FmiamqnlQgEqyPEQO/y7iY/Z9Qd1PEdojjqTTuDegiG6VjMuJvHyHrjoGbwwwsIysktyA+Rt1kTF5bgKJYXpe5J9JBSTCq3GATM0I0fLyGnQXPlpY6OfCHQtkq9m31+9LGNNTSmvT7u9JQZ3l1r0R/qNrVPBhM73E0xGa4hAnSxDLapAcXa/36ETqXVik7YUWgGeBjw5/xPVig+SyZHDXSe9MLaWZN7jlslF2Q7E1DlYmzRN0LXjI5vCyIwR47kw0sD3pWRfXW95YAYhUw7W4yV7aO4dSnbtt0SNdJL5Z6Qoqz07uV2JKvLgX/4zcYNvQ4J4djfD/W3waTKbPyIwPrVPmNXFg==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
