---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAMg69faPZ1Cgh68xxom9MySoVeFQkeWCYgWT/s3VYoxPNCdE01B3bm7u69UGOE83ewxj8bSLe3FGfBeP7Gc3humpCg3W+g1XMtnXVzDS6j0xom3QlJPwXoX9mqS4Ym7fQBK0K9CCZBFU0sBSRW1pCo0Tknz0Uq+ZBYruoMhl/vvlroarmo89VFQ2Xrl8ngdsju4lO/ejYz3MWKppQVEAlzB2jbbYwagAYUQ0sI4YplNQbvGQAOXxTdZtshD3aWMajpAdhP0xWzTAfjSLoCGjv6KUZPT/hQC5Yu/obg89FQuACP0D8HJhI2kE6ZVwZCWV4Q8AAhoNjIJAqVlXRm8aztT0Q2w2JADOzB/7luas+wSmvuog2WkZ1vs7Q/fbAsCIXPMupbm0UsZDtAFJM2OBXCb8ZCsForn0tc2Q81XG066oaCOq6RfQ+jkCefQJ0W+hghiikNAIDa80VRbFUmBi7r9Jlpz+qSgQ8R5A+0n1GsqspXLF62Cx83I8w4NKyl52YuOJ/qdnWC75z2c1V9K53xUMi3Ie1gpQfhp5Qq1WdsQ6xB+4JqOH1IgfMC3wzqFoBHaHCaReu3Y3jjf/qA143U+Ymc1n71EdyzpzqW+s2bPdTwhZD+xzyuxSXSyEMiumvmto4Wsu5oV3pSUflLC3twUX/TQggL6pZVtQdbdRZE4q/eL1FTfmGQEsrwoTqVWJvADN1pZJMZl5FuObHRKKtrD2Eelso33ByuxRGKQDtPH5vGfaxKGnopsAVQgs0UiW7jyZVFMA==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
