---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAs3rqm10TUPl7Bsg9UU6r4nwEpvvnfAkh9lo51shLvwvFHT3eUwy7hvnG8vzn70A3HZ5jYIqMt+w63ek0pT5aJY30zRnCo8A3CYTRUc18hVLb2bNkPN+I7e0P5ZRcpdsd1ugEaLS1DyO/krjeWQLp8Ms9mEg7/i4hU/D8WdSUevCaz7ND7mpBU2R/3c6o2SgrGBij8Y4/3MN7B8GxHS5Cf1lXEDy5RcYBfG4wy5WyaKqIleLuEMmDqaL6MruISlTuzQi74rADDwBq8wev7cADcT2NOar1F6TzKxdtR2X2ewbUXkRBDYt3OHV7QXJijNtCouQ1z5mGakeRLjRD4C39+vq1+79Ohe6LBEMJUXSYH+ejUBGClLQUSyt58KkQQg3hKkmwBKDXGxk3YG9xUfPg9O65lTYuA3Su2HFGMJtrVwSexO1qTeSaqzTm3PBfPevepx+zhzDoLdyF7V124b2yQcvgj1LpofcRyxxPjtqBjQBKsEMxDzSaKcZpUSWRcrx9AtoqZhOBsbjS5xa9kRfKUpZ6sKF4ZtXo0m+up1mp/mVDTOR419KgS96L61Lczc4fkS6cz0O3Syj8EGSWTFMwIjftFjJIo+lhGUFmaHg+qoXgO9n7AtddnPRPT3Js2NgSpEVlCamYlqQPK0xdR3VFXKBxvRYM/4cUtrTlsl5sQ5HvaEvVh4cn54Svq3ZwCh7xYMfDo9XffYqsPI1Cwg5ULqqhFVgPDdbWZS0oYAIvIA+qkN8ObYTlds0XS1MsN1O2UZJtxkHLmy6NvaPEZm2ZMQ4oWsBV6/GrwTaCVpFXs0gKTYUkTtBIrlNgNEg8F/gHnRAIfMbiFNpiO0FmDDe5i5dWVzzERRJt4ZLQrxaE5x2S2Qe/87IZ3hwX+FghtY6nozxFiSevAE6S6N9GdHM85Adn9FYRBssJctJRcK46OdjLC2Gdul446
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
