---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram-bot
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgBGGImleIOv43S2qu/Ounduy6AkYuTatYE1EW1BPqnGwASUkLQHYiFyCw8BNuCCgHE0oKWxA+PNpPMs/YMU0s1UstRtviL1ELMbdSJaz9n0CV4n3CkVGJlVKQ7/kdXrUaFbuvMlXzBog/XJmAKpFqAF9uJD7hiFbttRXBhcymW8/Gna14hSWqKF+LDIAnmNK47CK+RPDvpXDl71FVWuhTPHouxlD9ZCANQjSixCW65JL5+vCo65lwi4xTB04i4m+4DerqAPH7Pp6Ou3tc7zLoxW9aHQ5/VcHXnr72qqUU0jloPjvFThMEjBm82R+M3rzieaWjNNAEvxC8BWkBDXI8JOpHKwQhLOSscLzQ7D80LXk3AF2ZhzQCR8Q1l3irSr+5adJ/qamzoFPyNDcNw/yZ+J9KNSjWeWB6ip862Tt+Bvek5kP7L0DMqzAeik3yOrJ+qkPvcCjtoqyZ8saFaOkzoJ3cNyQpLqgIIVso8F56ka+IsWuRnDTNPPw6XCrPGGxw5N101lYhARY1v4fH72xfC3m/jHVMvtiIQPBTfrlHQumQB4qETu/pTon23p7u3AtAl/pqVHFMxGUkVN4pwjnJYTQLUVNo7WPtDvuhEqvgCXyYQ8MJe9XmKjawmIJc/bbWnOKpizQ/GXeWUzqwfrE7xdWBXgh49qw5gNCcvoapyIaoknyoQXeEIjKqHUvk3Rvt24Noli36lexRHlkPc3Lhvez93mznh7M3eq3c9rqDG+h5sQfebZNd9E+0AFFeaq
  template:
    metadata:
      name: alertmanager-telegram-bot
      namespace: monitoring
