---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAUEYsjzWbciEwWQPVqVElUl14SPZANtGwIs3DynCkcHnkNb01uwlHpLRb7YkHspFZbgEVvKDvbTRpI28hKBst1TtZvvvV+GP+1moF+99CSv7haiebaaJ6/zJG2WdBc+fuTfBLGA2Ovc6RXy73zu/TDQjQj5awSV8HUKtaJMFAy05qIpAy3gWHVetHsBoK4BR1AeWHg7SarNrqF/9tZ+LQqj5SkxkoC3zcywdr0g4UlJJg4hEdXbqyjID46C+hwKg1c15dekP6eXubTMeg7IyNdcnbIz1mGwBeUSWjh70utqIvWsYrtY5D51QrVB9g5ijHJZ2tCDCzulNlS9yOXSbKxIB2ovy0RkJ+uTcX2vSJlFk5KAab69kmYUHrbPkXDSAybTCFb6qB7pT6KvLRKK54Q7WE5ZDiRYsv0eOqA5ppNzMnmeSigrx+9EmwwaXixWoDzVHxmC/nd4FgTyJuuKTnT01FxY9G0qxSoXgX9dQSPAeODWe0VCt9bZh9ZY7ste0IXTqtYaeMXUXW3D/EF90vYA3SVakdlnN7wGgqFsYy7aTNp9dGLyXSADy9EJa36Tl6lDhys9/bd7nPXOWUMVzKPfOWFuyrh7x3hRDOpLAT+B273DIma57iEgMl6+mNeq9BbZCCkffFPEeFaW1Hv1FYO/6WS5xFLKDbVWGwtSw2Av2kL82yK/XgXLRu+pYgznRIwXgkcz3n/PraOOoVYreCiOyyJyqmQcVCBAuCVcAahlcEoPSxVGPr3ZIzXCA==
    admin-user: AgAZQ20fGhCsJbDAHj/Xu2qoOr3qmfLOGS+6SRxyvUiYKqSRKHSv6fnEUCcGC/27w56MFf8e7xZfPvTwDLeghSCyaE5mHECFLin47/W6JA6b+5kpNuPm6caD1PxGk9QoX38WzaymSDKvK7udHzZcCthf38norbrFRp7Lp1JI0ghjYJljT3kJ9Fc47l145QRGqMkubVqtxfMzLXOK/v1/Dx5h+2iEWmQZFe7SZeUHHKkzQN5S0m9hQuAMv+h6c2itFmcRNRalCl4j9ELj93fquiWlpxlOLTd7Hnnky6/NHR9UROO95E19RuQ/psgJhyuyH+utajoCiTbvU1x3hL+nEZSYx9R4Szah2falzpLOm4vk9ucbTX6KfUCrNSTrR6DpLIc1HcXi5sdLFNVPhw4Lhcsb/MJpHkUwKplio2M3YWGi61HL5GI+sYvQEyYj+MYGjCfQvav8zOmOlP83tCNoL15neMza5+kq3a1N1tymPx5wBmCqYkzPSUlpYIimMd6nZ5x8jjoEpBRbM3PvSRAjHmWgZQObmFTEhNnX6O8Lxz92nSWyY+rxCU8nxN4Ch1CDE4/tt9MH6tF1KmGxpppCbM5tcnl3NqRl7WoLQ+7Mee+w6OU/7CeSeFmK3mQ/YBQnSul49moP1pl7i+deTWQuYXiaYAlm9fVNSYP3FU6tO3clGxUPZQRZrk/hs9+mIo2jdagkpy75vg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
