apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: outegro
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/outegro/infra.git
    - https://charts.jetstack.io
    - https://bitnami-labs.github.io/sealed-secrets
  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: databases
      server: https://kubernetes.default.svc
    - namespace: messaging
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
