---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: databases
spec:
  encryptedData:
    redis-password: AgAJI9MYR4Az7Hx2CA5KsfYzp2O2aw5sDh12J/5hz/VzOzBw3+XQpqeI/8pSoIAPS7CUEnbnvI/STZeO6YSG/8GXtBx6kpN68tAauDIMyF1GD1zyFBdTTAyoN0hMT9Na9lwAZAdgcoVK9Vwl9qNAhPOMl25dl/LqURK6cyY2azVq5AnrwC6H0t6Bp+D5AvMX3MhrWc8rUH7eAr3CFXX/T12bkGdfVbJcwnvH3KqJ/9xtRqQ0Ko8OdN2DwxeLcPjH5YSHY8263tYrYd9fLhJdhVveS3lFS8r37yNc6CC5hsDYYzipbxWCDAdo/YQMJaT/E09Yw+XE5q+y9MQXIztBygF16TQHfatwzspQqOokk9COv1wzYri8emkYc8UvzhAIJ+kI9fquN4g6K+zlBCq0WGwL7b49n39oB4M62AjY47hM/amxZX19jMJhyycOpO0w4+ty4IHzAk1YiFJwchsmcm/+zhQGNxve3hl0FLhEXkrP8TNv8lkvFQlHmLZsd6BTUOXEgmvE98ygWCn6nE32FcJ4Og3TugWbCiwFKRXFspXXpatKLn/dk5yugqO5wc2FutWjZBiHVb382NP2GrDFWer7O5Q5sutmBBLhh6Mb/4jw07Xn6aBsFo+/JGcGAnejbunlJ5vuvSFl7u6FBXqlZ1wSFmpD9jt1rBzG74mvY0CcG6/yINhFL9Zt5DDRxFISBxM72aC8IQuZ2sRZppT8md84huSlenxVQMT1EsKlxDJDF5wuhFxCXQiqajWaUa665eI=
  template:
    metadata:
      name: redis-auth
      namespace: databases
